<?php

namespace App\Controller\Common;

use App\Service\AdminAuthService;

class AdminAuthBase extends AdminLoginBase
{
    //获取所有的权限
    protected function onRequest(?string $action): ?bool
    {
        $flag = parent::onRequest($action); // TODO: Change the autogenerated stub
        if ($flag) {
            //证明已经被登录成功,接下来检查权限
            $path_info = $this->request()->getServerParams()['path_info'];
            //找到路由，开始操作
            $admin_auth = AdminAuthService::SelectAdminAuth();
            if (!$admin_auth) {
                $this->Error('路由信息不存在!', null, '/admin/login');
                return false;
            }
            $admin_auth_ids = AdminAuthService::FindAdminAuthGroupByAdminId($this->GetAdminId());
            $auth_ids = explode(",", $admin_auth_ids);
            foreach ($admin_auth as $auth_k => $auth_value) {
                //找到路由
                if ($auth_value['url'] == $path_info) {
                    //进来了才算有
                    foreach ($auth_ids as $auth_id_key => $auth_id) {
                        if ($auth_value['id'] == $auth_id) {
                            return true;
                        }
                    }
                }
            }
            $this->Permission('权限不足,请联系管理员', null, '/admin/login');
        }
        return false;
    }
}